site_name: geodesic_dome
repo_url: https://github.com/gheleguen/geodesic_dome.git
edit_uri: -/edit/main/docs/

nav:
    - Introduction: README.md
    - 1. Les connecteurs: connecteurs_a_goupilles.md
    - Voie abandonnées:
      - Connecteurs imbriqués: connecteurs_imbriques.md
      - Connecteurs à rotules: connecteurs_a_rotules.md

 
theme:
    name: material
    palette:
      primary: yellow

plugins:
  - search

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
