site_name: remorques_ateliers
nav:
    - Readme: README.md
    - Voie abandonnées:
      - Connecteurs à rotules DIY: connecteurs_a_rotules.md
        
theme:
    name: material
    palette:
      primary: blue

plugins:
  - search
  - i18n:
      default_language: fr
      languages:
        fr: Français

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
