site_name: geodesic_dome
nav:
    - Introduction: README.md
    - 1. Les connecteurs: connecteurs_imbriques.md
    - Voie abandonnées:
      - Connecteurs à rotules DIY: connecteurs_a_rotules.md
        
theme:
    name: material
    palette:
      primary: yellow

plugins:
  - search

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
